WebApplication5/Models/ViewModel/PlayerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication5.Models.ViewModel
{
    public class PlayerViewModel
    {

        public int PlayerId { get; set; }

        [Required, StringLength(50, ErrorMessage = "Player name is requred"),
            Display(Name = "Player Name")]
        public string PlayerName { get; set; }

        [Required, Column(TypeName = "date"), Display(Name = "JOin date"),
            DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime JoinDate { get; set; }

        [EnumDataType(typeof(PlayerGrade))]
        public PlayerGrade? PlayerGrade { get; set; }

        public String PicturePath { get; set; }
        public HttpPostedFileBase Picture { get; set; }
        //Foreign key
        [ForeignKey("Sports")]
        public int SportsId { get; set; }
        //Navigation property
        public virtual Sports Sports { get; set; }
    }
}

WebApplication5/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using WebApplication5.Models;
using WebApplication5.Models.ViewModel;
using PagedList;
namespace WebApplication5.Controllers
{
    public class PlayersController : Controller
    {
        private readonly ClubDbContext db = new ClubDbContext();
        // GET: Players
        public ActionResult Index(int  Page=1)
        {
            var players = db.Players.Include("sports");
            return View(players.OrderBy(x => x.PlayerId).ToPagedList(Page, 3));

        }

        public ActionResult Create()
        {
            ViewBag.sports = new SelectList(db.Sports, "SportsId", "SportsName");
            return View();
        }

        [HttpPost]
        public ActionResult Create(PlayerViewModel pvm)
        {
            if (ModelState.IsValid)
            {
                //for save image
                string filePath = Path.Combine("~/Images", Guid.NewGuid().ToString() + 
                    Path.GetExtension(pvm.Picture.FileName));

                pvm.Picture.SaveAs(Server.MapPath(filePath));

                //for player
                Player player = new Player
                {
                    PlayerName = pvm.PlayerName,
                    JoinDate = pvm.JoinDate,
                    PlayerGrade = pvm.PlayerGrade,
                    SportsId = pvm.SportsId,
                    PicturePath = filePath
                };
                db.Players.Add(player);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.sports = new SelectList(db.Sports, "SportsId", "SportsName");
            return View(pvm);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            PlayerViewModel pvm = new PlayerViewModel
            {
                PlayerId = player.PlayerId,
                PlayerName = player.PlayerName,
                JoinDate = player.JoinDate,
                PlayerGrade = player.PlayerGrade,
                SportsId = player.SportsId,
                PicturePath = player.PicturePath
            };
            ViewBag.sports = new SelectList(db.Sports, "SportsId", "SportsName" );
            return View(pvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PlayerViewModel pvm)
        {
            if (ModelState.IsValid)
            {
                string filePath = pvm.PicturePath;
                if (pvm.Picture !=null)
                {
                     filePath = Path.Combine("~/Images", Guid.NewGuid().ToString() +
                         Path.GetExtension(pvm.Picture.FileName));
                    pvm.Picture.SaveAs(Server.MapPath(filePath));
                    Player player = new Player
                    {
                        PlayerId = pvm.PlayerId,
                        PlayerName = pvm.PlayerName,
                        JoinDate = pvm.JoinDate,
                        PlayerGrade = pvm.PlayerGrade,
                        SportsId = pvm.SportsId,
                        PicturePath = filePath
                    };
                    db.Entry(player).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");


                }
                else
                {
                    Player player = new Player
                    {
                        PlayerId = pvm.PlayerId,
                        PlayerName = pvm.PlayerName,
                        JoinDate = pvm.JoinDate,
                        PlayerGrade = pvm.PlayerGrade,
                        SportsId = pvm.SportsId,
                        PicturePath = filePath
                    };
                    db.Entry(player).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.sports = new SelectList(db.Sports, "SportsId", "SportsName",pvm.SportsId);
            return View(pvm);
        }

        public ActionResult Delete(int ?id)
        {
            if (id ==null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);

            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }
        [HttpPost ,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id )
        {
            Player player = db.Players.Find(id);
            db.Players.Remove(player);
            db.SaveChanges();
            return RedirectToAction("Index");
        }







    }

    
}

WebApplication5/Views/Players/Create.cshtml
@model WebApplication5.Models.ViewModel.PlayerViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


<div class="row">
    <div class="col">
        @using (Html.BeginForm("Create", "Players", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken();
            <h2 class="display-4">Add New Player</h2>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row mb-2">
                @Html.LabelFor(x => x.PlayerName, htmlAttributes: new { @class = "col-form-label col-2" })
                <div class="col-8">
                    @Html.EditorFor(x => x.PlayerName, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="col-2">
                    @Html.ValidationMessageFor(x => x.PlayerName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row mb-2">
                @Html.LabelFor(x => x.PlayerGrade, htmlAttributes: new { @class = "col-form-label col-2" })
                <div class="col-8">
                    @Html.EnumDropDownListFor(x => x.PlayerGrade, "---Select---", htmlAttributes: new { @class = "form-select" })
                </div>
                <div class="col-2">
                    @Html.ValidationMessageFor(x => x.PlayerGrade, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row mb-2">
                @Html.LabelFor(x => x.SportsId, htmlAttributes: new { @class = "col-form-label col-2" })
                <div class="col-8">
                    @Html.DropDownListFor(x => x.SportsId, ViewBag.sports as SelectList, "---Select---", htmlAttributes: new { @class = "form-select" })
                </div>
                <div class="col-2">
                    @Html.ValidationMessageFor(x => x.SportsId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row mb-2">
                @Html.LabelFor(x => x.JoinDate, htmlAttributes: new { @class = "col-form-label col-2" })
                <div class="col-8">
                    @Html.EditorFor(x => x.JoinDate, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                </div>
                <div class="col-2">
                    @Html.ValidationMessageFor(x => x.JoinDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row mb-2">
                @Html.LabelFor(x => x.Picture, htmlAttributes: new { @class = "col-form-label col-2" })
                <div class="col-8">
                    @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
                </div>
                <div class="col-2">
                    @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-10 offset-2">
                    <button type="reset" class="btn btn-secondary"><i class="fa fa-refresh"></i> Reset values</button>
                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save Data </button>
                </div>
            </div>
        }
        <div>
            <button onclick="location.href='@Url.Action("Index", "Players")'"
                    class="btn btn-link btn-sm" style="text-decoration:none;">
            <i class="fa fa-arrow-circle-left"></i> Back to list</button>
        </div>
    </div>
</div>

WebApplication5/Views/Players/Delete.cshtml
@model WebApplication5.Models.Player

@{
    ViewBag.Title = "Delete";
}

<h3 class="display-4 text-bg-danger text-lg-center" >Are you sure you want to delete this Player?</h3>
<div>
    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Sports.SportsName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sports.SportsName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlayerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlayerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JoinDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JoinDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlayerGrade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlayerGrade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PicturePath)
        </dt>

        <dd>
            <img src="@Url.Content(Model.PicturePath)" width="32"  style="border-radius: 10px;"/>
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication5/Views/Players/Edit.cshtml
@model WebApplication5.Models.ViewModel.PlayerViewModel
@{
    ViewBag.Title = "Edit";
}



<div class="row">
    <div class="col">
        @using (Html.BeginForm("Edit", "Players", FormMethod.Post, new 
        { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(x=>x.PlayerId)
            @Html.AntiForgeryToken();
            <h2 class="display-4">Add New Player</h2>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row mb-2">
                @Html.LabelFor(x => x.PlayerName, htmlAttributes: new { @class = "col-form-label col-2" })
                <div class="col-8">
                    @Html.EditorFor(x => x.PlayerName, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="col-2">
                    @Html.ValidationMessageFor(x => x.PlayerName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row mb-2">
                @Html.LabelFor(x => x.PlayerGrade, htmlAttributes: new { @class = "col-form-label col-2" })
                <div class="col-8">
                    @Html.EnumDropDownListFor(x => x.PlayerGrade, "---Select---", htmlAttributes: new { @class = "form-select" })
                </div>
                <div class="col-2">
                    @Html.ValidationMessageFor(x => x.PlayerGrade, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row mb-2">
                @Html.LabelFor(x => x.SportsId, htmlAttributes: new { @class = "col-form-label col-2" })
                <div class="col-8">
                    @Html.DropDownListFor(x => x.SportsId, ViewBag.sports as SelectList, "---Select---", htmlAttributes: new { @class = "form-select" })
                </div>
                <div class="col-2">
                    @Html.ValidationMessageFor(x => x.SportsId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row mb-2">
                @Html.LabelFor(x => x.JoinDate, htmlAttributes: new { @class = "col-form-label col-2" })
                <div class="col-8">
                    @Html.EditorFor(x => x.JoinDate, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                </div>
                <div class="col-2">
                    @Html.ValidationMessageFor(x => x.JoinDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row mb-2">
                @Html.LabelFor(x => x.Picture, htmlAttributes: new { @class = "col-form-label col-2" })
                <div class="col-8">
                    @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
                </div>
                <div class="col-2">
                    @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
                  
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-10 offset-2">
                    <input type="reset"class="btn btn-secondary"value="Reset Values" />
                    <input type="submit"class="btn btn-primary"value="Update Data"/>
               
                </div>
            </div>
        }
        <div>
            <button onclick="location.href='@Url.Action("Index", "Players")'"
                    class="btn btn-link btn-sm" style="text-decoration:none;">
                <i class="fa fa-arrow-circle-left"></i> Back to list
            </button>
        </div>
    </div>
    </div>

WebApplication5/Views/Players/Index.cshtml
@model IEnumerable<WebApplication5.Models.Player>

@{
    ViewBag.Title = "Index";
}
@using PagedList;
@using PagedList.Mvc;
<h2 class="display-4">Player List</h2>
<div class="d-flex justify-content-end">
 
    <button onclick="location.href='@Url.Action("Create", "Players")'" class="btn btn-primary btn-sm"
            style="text-decoration:none;">
        <i class="fa fa-plus"></i> Add New
    </button>
</div>

<div class="row">
    <div class="col">
        <table class="table table-bordered table-striped table-sm,mt-1 text-center">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(x => x.PlayerName)</th>
                    <th>@Html.DisplayNameFor(x => x.Sports.SportsName)</th>
                    <th>@Html.DisplayNameFor(x => x.JoinDate)</th>
                    <th>@Html.DisplayNameFor(x => x.PlayerGrade)</th>
                    <th>Picture</th>
                    <th> Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(x => item.PlayerName)</td>
                        <td>@Html.DisplayFor(x => item.Sports.SportsName)</td>
                        <td>@Html.DisplayFor(x => item.JoinDate)</td>
                        <td>@Html.DisplayFor(x => item.PlayerGrade)</td>
                        <td>
                            <img src="@Url.Content(item.PicturePath)" width="32" 
                                 style="border-radius: 8px;" />
                        </td>
                        <td>
                            <button onclick="location.href='@Url.Action("Edit", "Players",
                                                           new {id=item.PlayerId})'"
                                    class="btn btn-success btn-sm"><i class="fa fa-pencil"></i></button>
                            <button onclick="location.href='@Url.Action("Delete", "Players",
                                                           new {id=item.PlayerId})'"
                                    class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>
                        </td>
                    </tr>
                }
        </table>
        <div class="d-flex justify-content-end">
            @Html.PagedListPager(Model as IPagedList,page=> Url.Action("Index", new {page}))
        </div> 
    </div>
</div>
@section styles{
    <link href="~/Content/PagedList.css" rel="stylesheet" />
}